name: EFSTG
channels:
  - pytorch
  - conda-forge
  - pyg
  - defaults
dependencies:
  - python=3.9
  - numpy>=1.26.0
  - pandas>=2.0.0
  - pytorch>=1.13.0
  - networkx>=3.0
  - scipy>=1.13.0
  - scikit-learn>=1.6.0
  - matplotlib>=3.9.0
  - tqdm
  - pyyaml
  - h5py
  - pyg::pyg
  - pip
  - pip:
    - optuna>=4.0.0
    - torchinfo>=1.8.0